AT_Guilherme_Duques/Models/ErrorViewModel.cs
using System;

namespace AT_Guilherme_Duques.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AT_Guilherme_Duques/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AT_Guilherme_Duques.Models
{
    public class Pessoa
    {
        public int iD { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }

        [DataType(DataType.Date)]

        public DateTime DataPessoa { get; set; }


    }
}

AT_Guilherme_Duques/Controllers/HomeController.cs
using AT_Guilherme_Duques.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AT_Guilherme_Duques.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AT_Guilherme_Duques/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AT_Guilherme_Duques.Data;
using AT_Guilherme_Duques.Models;
using AT_Guilherme_Duques.Repository;

namespace AT_Guilherme_Duques.Controllers
{
    public class PessoasController : Controller
    {
        private readonly AT_Guilherme_DuquesContext _context;

        public PessoasController(AT_Guilherme_DuquesContext context)
        {
            _context = context;
        }

        // GET: Friends
        public IActionResult Index(string searchString)
        {
            var friends = from f in _context.Pessoa select f;
            if (!String.IsNullOrEmpty(searchString))
            {
                friends = friends.Where(s => s.nome.Contains(searchString));
            }
            return View(friends.ToList());
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (PessoaRepository.Details(id, _context) == null)
            {
                return NotFound();
            }
            return View(PessoaRepository.Details(id, _context));
        }

        // GET: Pessoas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("iD,nome,sobrenome,DataPessoa")] Pessoa friend)
        {
            if (ModelState.IsValid)
            {
                _context.Add(friend);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(friend);
        }

        //GET: Friends/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (PessoaRepository.Edit(id, _context) == null)
            {
                return NotFound();
            }
            return View(PessoaRepository.Edit(id, _context));
        }

        // POST: Friends/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("iD,nome,sobrenome,DataPessoa")] Pessoa pessoa)
        {
            if (id != pessoa.iD)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pessoa);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoaExists(pessoa.iD))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }


        private bool PessoaExists(int id)
        {
            return _context.Pessoa.Any(e => e.iD == id);
        }


        // GET: Friends/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (PessoaRepository.Delete(id, _context) == null)
            {
                return NotFound();
            }

            return View(PessoaRepository.Delete(id, _context));
        }

        // POST: Friends/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var friend = _context.Pessoa.Find(id);
            _context.Pessoa.Remove(friend);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

AT_Guilherme_Duques/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AT_Guilherme_Duques/Views/Pessoas/Create.cshtml
@model AT_Guilherme_Duques.Models.Pessoa

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label">Nome</label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sobrenome" class="control-label">Sobrenome</label>
                <input asp-for="sobrenome" class="form-control" />
                <span asp-validation-for="sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataPessoa" class="control-label">Data de Aniversario</label>
                <input asp-for="DataPessoa" class="form-control" />
                <span asp-validation-for="DataPessoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AT_Guilherme_Duques/Views/Pessoas/Delete.cshtml
@model AT_Guilherme_Duques.Models.Pessoa

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Você tem certeza que quer excluir essas informacões?</h3>
<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nome
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            Sobrenome
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sobrenome)
        </dd>
        <dt class = "col-sm-2">
            Data de Aniversario
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataPessoa)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="iD" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para a lista</a>
    </form>
</div>

AT_Guilherme_Duques/Views/Pessoas/Details.cshtml
@model AT_Guilherme_Duques.Models.Pessoa

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nome
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            Sobrenome
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.sobrenome)
        </dd>
        <dt class = "col-sm-2">
            Data de Aniversario
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataPessoa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.iD">Editar</a> |
    <a asp-action="Index">Voltar para a listat</a>
</div>

AT_Guilherme_Duques/Views/Pessoas/Edit.cshtml
@model AT_Guilherme_Duques.Models.Pessoa

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="iD" />
            <div class="form-group">
                <label asp-for="nome" class="control-label">Nome</label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sobrenome" class="control-label">Sobrenome</label>
                <input asp-for="sobrenome" class="form-control" />
                <span asp-validation-for="sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataPessoa" class="control-label">Data de Aniversario</label>
                <input asp-for="DataPessoa" class="form-control" />
                <span asp-validation-for="DataPessoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AT_Guilherme_Duques/Views/Pessoas/Index.cshtml
@model IEnumerable<AT_Guilherme_Duques.Models.Pessoa>

@{
    ViewData["Title"] = "Index";
}

<h1>Listas dos aniversarios</h1>

<p>
    <a asp-action="Create">Criar novo</a>
</p>

<form asp-controller="Pessoas" asp-action="Index">
    <p>
        Buscar: <input type="text" name="SearchString" />
        <input type="submit" value="filtro" />
    </p>

</form>

@if (Model.Count() != 0)
{
    DateTime currentDate = DateTime.Today;
    <div class="panel panel-primary">
        <div class="panel-heading">
            ANIVERSARIANTE DO DIA
        </div>
        <table class="table">
            <tr border="1px" bgcolor="#CCC">
                <th>
                    Nome
                </th>
                <th>
                    Sobrenome
                </th>
                <th>
                    Data de Aniversario
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {

                if (item.DataPessoa.Month == currentDate.Month && item.DataPessoa.Day == currentDate.Day)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.sobrenome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DataPessoa)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.iD">Editar</a> |
                            <a asp-action="Details" asp-route-id="@item.iD">Detalhes</a> |
                            <a asp-action="Delete" asp-route-id="@item.iD">Deletar</a>
                        </td>
                    </tr>
                }

            }
        </table>
    </div>
    <br>

    <div class="panel panel-primary">
        <div class="panel-heading">
            Lista de aniversario dos amigos
        </div>
        <table class="table">
            <tr border="1px" bgcolor="#CCC">
                <th>
                    Nome
                </th>
                <th>
                    Sobrenome
                </th>
                <th>
                    Data de Aniversario
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                //if (item.FriendBirthday.Month != currentDate.Month && item.FriendBirthday.Day != currentDate.Day)
                //{
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.sobrenome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataPessoa)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.iD">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.iD">Detalhes</a> |
                        <a asp-action="Delete" asp-route-id="@item.iD">Deletar</a>
                    </td>
                </tr>
                //}
            }

        </table>
    </div> }
else
{
    <h1>Nenhum Usuário Cadastrado</h1>}
<div>
    <a asp-action="Index">Voltar a lista</a>
</div>

AT_Guilherme_Duques/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AT_Guilherme_Duques</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AT_Guilherme_Duques</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AT_Guilherme_Duques - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>